name: RushGame
version: 1.0.0
main: com.minigames.rushgame.RushGamePlugin
api-version: 1.20
authors: [Web Workers]
description: Custom rush minigame

depend: [MinigamesCore]
softdepend: [Vault, PlaceholderAPI]

commands:
  rush:
    description: Main rush game command
    usage: /rush <join|leave|info>
    permission: rushgame.use

permissions:
  rushgame.use:
    description: Basic rush game permission
    default: true
  rushgame.admin:
    description: Admin rush game permission
    default: op